name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install ts-node
        run: npm install -g ts-node

      - name: Generate db
        run: npm run generatedb

      - name: Build prod
        run: npm run buildprod

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Download build
        if: success()
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: lfpe
